server:
  port: 8080
  servlet:
    context-path: /good-lodging

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/good-lodging"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: good-lodging
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangnv7979@gmail.com
    password: qniwywrntatrvugj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  email:
      brevo-url: https://api.brevo.com
feign:
  client:
    config:
      default:
        decoder: jacksonDecoder
jwt:
  signerKey: "H+FtQksllnPVgdl7v1ERls5/x/cAY7YKnRqKY1eekYrKYF0ktPHqjul8sSdrsBaY"
  valid-duration: 60 #seconds
  refreshable-duration: 120 # seconds
upload:
  uploadDir: "E:/uploads/"
jhipster:
  security:
    authentication:
      jwt:
        base64-secret: "yourBase64SecretHere"  # hoặc sử dụng "secret" thay vì "base64-secret"
        token-validity-in-seconds: 3600  # 1 giờ
        token-validity-in-seconds-for-remember-me: 2592000  # 30 ngày
